export type Horizon = "today" | "3d" | "7d";
export type Section = "temperature" | "precipitation" | "wind";
export type View = "day" | "period";
export type DataStatus = "verified" | "partially_verified" | "demo";
export type Region = {
  id: string;
  name: string;
  short_name: string;
  name_prepositional: string;
  name_genitive: string;
  federal_district: string;
  primary_timezone: string;
  has_multiple_timezones: boolean;
  default_point_id: string;
  map_center_latitude: number;
  map_center_longitude: number;
  map_zoom: number;
  data_status: DataStatus;
  point_count: number;
  geojson_available: boolean;
};
export type ModelValues = Record<string, number | null>;
export type Statistics = {
  count: number;
  complete: boolean;
  consensus_available: boolean;
  mean?: number;
  median?: number | null;
  minimum?: number;
  minimum_source?: string;
  maximum?: number;
  maximum_source?: string;
  range?: number;
  standard_deviation?: number;
  agreement?: string;
};
export type Point = {
  id: string;
  region_id: string;
  name: string;
  latitude: number;
  longitude: number;
  timezone: string;
  point_type: string;
  is_regional_center: boolean;
  weight: number;
};
export type PointSummary = {
  point: Point;
  mean_temperature: number;
  models: ModelValues;
  minimum: number;
  minimum_source?: string;
  maximum: number;
  maximum_source?: string;
  spread: number;
  agreement: string;
  precipitation: Statistics;
  wind_speed: Statistics;
  humidity: Statistics;
  pressure: Statistics;
  max_gust: number | null;
  max_gust_source?: string;
  precipitation_analysis: {
    daily_total: Statistics & { model_values: ModelValues };
    relative_spread_pct: number | null;
    hourly_peak: Statistics;
    peak_time: string | null;
    peak_model: string | null;
    peak_value: number | null;
    event_start: string | null;
    event_end: string | null;
    duration_hours: number;
    event_count: number;
    hours_above_threshold: number;
    confirming_models: number;
    start_time_disagreement_hours: number | null;
  };
  wind_analysis: {
    mean_speed: Statistics & { model_values: ModelValues };
    maximum_speed: Statistics & { model_values: ModelValues };
    maximum_gust: Statistics & { model_values: ModelValues };
    maximum_gust_time: string | null;
    maximum_gust_model: string | null;
    maximum_gust_value: number | null;
    circular_mean_direction_deg: number | null;
    direction_label: string | null;
    directions_by_model: ModelValues;
    direction_labels_by_model: Record<string, string | null>;
    maximum_direction_disagreement_deg: number | null;
    direction_disagreement_models: string[];
    direction_agreement: string;
    maximum_direction_change_deg?: number | null;
    direction_change_start?: string | null;
    direction_change_end?: string | null;
    strong_wind_start: string | null;
    strong_wind_end: string | null;
    strong_wind_duration_hours: number;
  };
  incomplete: boolean;
};
export type Hourly = {
  point_id: string;
  point_name: string;
  forecast_time_local: string;
  models: ModelValues;
  statistics: Statistics;
  agreement: string;
};
export type DailyModelSummary = {
  temperature_min: number;
  temperature_max: number;
  temperature_mean: number;
  precipitation_sum: number;
  wind_speed_mean: number;
  wind_gust_max: number;
};
export type DailySummary = {
  date: string;
  available: boolean;
  mean_temperature: number;
  minimum_temperature: number;
  maximum_temperature: number;
  precipitation_sum: number;
  mean_wind_speed: number;
  max_gust: number;
  mean_humidity: number;
  mean_pressure: number;
  spread: number;
  agreement: string;
  models: Record<string, DailyModelSummary | null>;
};
export type Extreme = {
  value: number;
  unit: string;
  date: string;
  forecast_time: string;
  point_name: string;
  model: string;
};
export type PeriodSummary = {
  period_start: string;
  period_end: string;
  warmest_day: DailySummary;
  coldest_day: DailySummary;
  wettest_day: DailySummary;
  gustiest_day: DailySummary;
  most_divergent_day: DailySummary;
  temperature: {
    absolute_maximum: Extreme;
    absolute_minimum: Extreme;
    mean: number;
  };
  precipitation: {
    point: Point;
    models: Record<string, number | null>;
    statistics: Statistics;
  };
  wind: {
    maximum_speed: Extreme;
    maximum_gust: Extreme;
    circular_mean_direction: number | null;
  };
};
export type Forecast = {
  region: Region;
  region_id: string;
  region_name: string;
  horizon: Horizon;
  period_start: string;
  period_end: string;
  selected_date: string;
  available_dates: string[];
  data_mode: "mock" | "live";
  model_availability: Record<string, boolean>;
  warnings: string[];
  last_updated: string;
  points: PointSummary[];
  hourly: Hourly[];
  daily_summaries: DailySummary[];
  period_summary: PeriodSummary;
};
export type PointForecast = {
  region: Region;
  point: Point;
  horizon: Horizon;
  selected_date: string;
  available_dates: string[];
  series: Record<string, Hourly[]>;
  daily_aggregates: Array<Record<string, string | number | null>>;
  period_summary: PeriodSummary;
  warnings: string[];
};
export type WeatherInsight = {
  category: "precipitation" | "wind";
  severity: "info" | "attention" | "notable";
  reason_code: string;
  title: string;
  description: string;
  explanation: string;
  period_start: string | null;
  period_end: string | null;
  point_id: string | null;
  point_name: string | null;
  models: string[];
  values: Record<string, string | number | null>;
};
export type InsightsResponse = {
  region: Region;
  region_id: string;
  region_name: string;
  horizon: Horizon;
  period_start: string;
  period_end: string;
  selected_date: string;
  disclaimer: string;
  precipitation: { items: WeatherInsight[]; total: number };
  wind: { items: WeatherInsight[]; total: number };
};
